version: '3'
services:
  notebook:
    build:
      context: ./notebook
      args:
        NOTEBOOK_VERSION: ${NOTEBOOK_VERSION}
    ports:
      - "8888:8888"
    volumes:
      - ${PROJECT_ROOT}:/home/jovyan/work
    depends_on:
      - mysql
  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_ROOT}:/home/jovyan/work
      - db:/var/lib/mysql
volumes:
    db:
